name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
        run: git remote add space https://huggingface.co/spaces/RainPoo/Automated-Interview-Filtering
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: |
          git config --global user.email "rain7464@gmail.com"
          git config --global user.name "Poo-wei-chien"
          git push --force https://RainPoo:$HF_TOKEN@huggingface.co/spaces/RainPoo/Automated-Interview-Filtering main
